version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

executors:
  docker-python:
    docker:
      - image: cimg/base:2023.02

jobs:
  build-and-push:
    executor: docker-python
    resource_class: small
    parameters:
      repo-name:
        type: string
        description: Name of the ECR repo
      folder-name:
        type: string
        description: Name of the folder containing the code
    steps:
      - checkout
      - run:
          name: Check changes in crawler folder
          command: |
            REF=HEAD
            SINCE=origin/main
            DIR_TO_CHECK=<< parameters.folder-name >>

            MERGE_BASE=$(git merge-base ${SINCE} ${REF})
            FILES_CHANGED=$(git diff --name-only ${MERGE_BASE}..${REF} -- ${DIR_TO_CHECK})

            if [[ -n $FILES_CHANGED ]]; then
              echo 'export CHANGES_IN_FOLDER="TRUE"' >> "$BASH_ENV"
              source $BASH_ENV
            fi
            echo $CHANGES_IN_FOLDER
      - when:
          condition: $CHANGES_IN_FOLDER
          steps:
            - aws-ecr/build-and-push-image:
                repo: << parameters.repo-name >>
                path: << parameters.folder-name >>
                registry-id: AWS_ECR_REGISTRY_ID
                region: us-east-1
                setup-remote-docker: true
                role-arn: $AWS_ROLE_OIDC

workflows:
  build-and-deploy:
    jobs:
      - build-and-push:
          name: build-crawler
          repo-name: flights-crawler
          folder-name: flight-crawler
          context:
            - CircleCI-OIDC
      - build-and-push:
          name: build-manager
          repo-name: flights-manager
          folder-name: flight-manager
          context:
            - CircleCI-OIDC
