version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

executors:
  docker-python:
    docker:
      - image: cimg/base:2023.02

jobs:
  build-and-push:
    executor: docker-python
    resource_class: small
    steps:
      - checkout
      - run:
          name: Check changes in crawler folder
          command: |
            REF=HEAD
            SINCE=origin/main
            DIR_TO_CHECK=flight-crawler

            MERGE_BASE=$(git merge-base ${SINCE} ${REF})
            FILES_CHANGED=$(git diff --name-only ${MERGE_BASE}..${REF} -- ${DIR_TO_CHECK})

            if [[ -n $FILES_CHANGED ]]; then
              echo 'export CRAWLER_CHANGES_IN_FOLDER="TRUE"' >> "$BASH_ENV"
            fi
            echo $CRAWLER_CHANGES_IN_FOLDER
      - when:
          condition:
            equal: ["TRUE", $CRAWLER_CHANGES_IN_FOLDER]
          steps:
            - aws-ecr/build-and-push-image:
                repo: flights-crawler
                path: flight-crawler
                registry-id: AWS_ECR_REGISTRY_ID
                region: us-east-1
                setup-remote-docker: true
      - run:
          name: Check changes in manager folder
          command: |
            REF=HEAD
            SINCE=origin/main
            DIR_TO_CHECK=flight-manager

            MERGE_BASE=$(git merge-base ${SINCE} ${REF})
            FILES_CHANGED=$(git diff --name-only ${MERGE_BASE}..${REF} -- ${DIR_TO_CHECK})

            if [[ -n $FILES_CHANGED ]]; then
              echo 'export MANAGER_CHANGES_IN_FOLDER="TRUE"' >> "$BASH_ENV"
            fi
            echo $MANAGER_CHANGES_IN_FOLDER
      - when:
          condition:
            equal: ["TRUE", $MANAGER_CHANGES_IN_FOLDER]
          steps:
            - aws-ecr/build-and-push-image:
                repo: flights-manager
                path: flight-manager
                registry-id: AWS_ECR_REGISTRY_ID
                region: us-east-1
                setup-remote-docker: true

workflows:
  build-and-deploy:
    jobs:
      - build-and-push
